GBool upsideDown (  ) ;
GBool useDrawChar (  ) ;
GBool useTilingPatternFill (  ) ;
GBool useShadedFills ( int type ) ;
GBool useFillColorStop (  ) ;
GBool useDrawForm (  ) ;
GBool interpretType3Chars (  ) ;
GBool needNonText (  ) ;
GBool needCharCount (  ) ;
GBool needClipToCropBox (  ) ;
void setDefaultCTM ( double * ctm ) ;
void startPage ( int pageNum, GfxState * state, XRef * xref ) ;
void endPage (  ) ;
void dump (  ) ;
void cvtDevToUser ( double dx, double dy, double * ux, double * uy ) ;
void cvtUserToDev ( double ux, double uy, int * dx, int * dy ) ;
double * getDefCTM (  ) ;
double * getDefICTM (  ) ;
void saveState ( GfxState * A ) ;
void restoreState ( GfxState * A ) ;
void updateAll ( GfxState * state ) ;
void updateCTM ( GfxState * A, double B, double C, double D, double E, double F, double G ) ;
void updateLineDash ( GfxState * A ) ;
void updateFlatness ( GfxState * A ) ;
void updateLineJoin ( GfxState * A ) ;
void updateLineCap ( GfxState * A ) ;
void updateMiterLimit ( GfxState * A ) ;
void updateLineWidth ( GfxState * A ) ;
void updateStrokeAdjust ( GfxState * A ) ;
void updateAlphaIsShape ( GfxState * A ) ;
void updateTextKnockout ( GfxState * A ) ;
void updateFillColorSpace ( GfxState * A ) ;
void updateStrokeColorSpace ( GfxState * A ) ;
void updateFillColor ( GfxState * A ) ;
void updateStrokeColor ( GfxState * A ) ;
void updateBlendMode ( GfxState * A ) ;
void updateFillOpacity ( GfxState * A ) ;
void updateStrokeOpacity ( GfxState * A ) ;
void updatePatternOpacity ( GfxState * A ) ;
void clearPatternOpacity ( GfxState * A ) ;
void updateFillOverprint ( GfxState * A ) ;
void updateStrokeOverprint ( GfxState * A ) ;
void updateOverprintMode ( GfxState * A ) ;
void updateTransfer ( GfxState * A ) ;
void updateFillColorStop ( GfxState * A, double B ) ;
void updateFont ( GfxState * A ) ;
void updateTextMat ( GfxState * A ) ;
void updateCharSpace ( GfxState * A ) ;
void updateRender ( GfxState * A ) ;
void updateRise ( GfxState * A ) ;
void updateWordSpace ( GfxState * A ) ;
void updateHorizScaling ( GfxState * A ) ;
void updateTextPos ( GfxState * A ) ;
void updateTextShift ( GfxState * A, double B ) ;
void saveTextPos ( GfxState * A ) ;
void restoreTextPos ( GfxState * A ) ;
void stroke ( GfxState * A ) ;
void fill ( GfxState * A ) ;
void eoFill ( GfxState * A ) ;
GBool tilingPatternFill ( GfxState * A, Gfx * B, Catalog * C, Object * D, double * E, int F, int G, Dict * H, double * I, double * J, int K, int L, int M, int N, double O, double P ) ;
GBool functionShadedFill ( GfxState * A, GfxFunctionShading * B ) ;
GBool axialShadedFill ( GfxState * A, GfxAxialShading * B, double C, double D ) ;
GBool axialShadedSupportExtend ( GfxState * A, GfxAxialShading * B ) ;
GBool radialShadedFill ( GfxState * A, GfxRadialShading * B, double C, double D ) ;
GBool radialShadedSupportExtend ( GfxState * A, GfxRadialShading * B ) ;
GBool gouraudTriangleShadedFill ( GfxState * state, GfxGouraudTriangleShading * shading ) ;
GBool patchMeshShadedFill ( GfxState * state, GfxPatchMeshShading * shading ) ;
void clip ( GfxState * A ) ;
void eoClip ( GfxState * A ) ;
void clipToStrokePath ( GfxState * A ) ;
void beginStringOp ( GfxState * A ) ;
void endStringOp ( GfxState * A ) ;
void beginString ( GfxState * A, GooString * B ) ;
void endString ( GfxState * A ) ;
void drawChar ( GfxState * A, double B, double C, double D, double E, double F, double G, CharCode H, int I, Unicode * J, int K ) ;
void drawString ( GfxState * A, GooString * B ) ;
GBool beginType3Char ( GfxState * A, double B, double C, double D, double E, CharCode F, Unicode * G, int H ) ;
void endType3Char ( GfxState * A ) ;
void beginTextObject ( GfxState * A ) ;
void endTextObject ( GfxState * A ) ;
void incCharCount ( int A ) ;
void beginActualText ( GfxState * A, GooString * B ) ;
void endActualText ( GfxState * A ) ;
void drawImageMask ( GfxState * state, Object * ref, Stream * str, int width, int height, GBool invert, GBool interpolate, GBool inlineImg ) ;
void setSoftMaskFromImageMask ( GfxState * state, Object * ref, Stream * str, int width, int height, GBool invert, GBool inlineImg, double * baseMatrix ) ;
void unsetSoftMaskFromImageMask ( GfxState * state, double * baseMatrix ) ;
void drawImage ( GfxState * state, Object * ref, Stream * str, int width, int height, GfxImageColorMap * colorMap, GBool interpolate, int * maskColors, GBool inlineImg ) ;
void drawMaskedImage ( GfxState * state, Object * ref, Stream * str, int width, int height, GfxImageColorMap * colorMap, GBool interpolate, Stream * maskStr, int maskWidth, int maskHeight, GBool maskInvert, GBool maskInterpolate ) ;
void drawSoftMaskedImage ( GfxState * state, Object * ref, Stream * str, int width, int height, GfxImageColorMap * colorMap, GBool interpolate, Stream * maskStr, int maskWidth, int maskHeight, GfxImageColorMap * maskColorMap, GBool maskInterpolate ) ;
void endMarkedContent ( GfxState * state ) ;
void beginMarkedContent ( char * name, Dict * properties ) ;
void markPoint ( char * name, Dict * properties ) ;
void opiBegin ( GfxState * state, Dict * opiDict ) ;
void opiEnd ( GfxState * state, Dict * opiDict ) ;
void type3D0 ( GfxState * A, double B, double C ) ;
void type3D1 ( GfxState * A, double B, double C, double D, double E, double F, double G ) ;
void psXObject ( Stream * A, Stream * B ) ;
void startProfile (  ) ;
GooHash * getProfileHash (  ) ;
GooHash * endProfile (  ) ;
GBool checkTransparencyGroup ( GfxState * A, GBool B ) ;
void beginTransparencyGroup ( GfxState * A, double * B, GfxColorSpace * C, GBool D, GBool E, GBool F ) ;
void endTransparencyGroup ( GfxState * A ) ;
void paintTransparencyGroup ( GfxState * A, double * B ) ;
void setSoftMask ( GfxState * A, double * B, GBool C, Function * D, GfxColor * E ) ;
void clearSoftMask ( GfxState * A ) ;
void processLink ( AnnotLink * A ) ;
GBool getVectorAntialias (  ) ;
void setVectorAntialias ( GBool A ) ;
